### ISSUE TITLE
Looping capability

### ISSUE THREAD

**Issue by BRE86** [AasheeshMahammad/insomnia-plugin-run-requests-parallel#2]
Hello Aasheesh. :)

I started using your plugin today, very efficient to run a full collection !

I need for my work to be able to loop X times a run.
Could it be a functionnality that you could add to your project ?

Thank again for your work,
BRE

**Comment by AasheeshMahammad** [comment]
Hi BRE,

Thank you for trying out my plugin and for your positive feedback! I'm glad to hear that it's been helpful for running your collections efficiently.

Regarding your request to add the ability to loop a run X times, I appreciate the suggestion! It's certainly a useful feature that could benefit many users.
I'm currently working on implementing this feature, I anticipate that the feature should be ready for release in the next few upcoming days.

Thanks again for reaching out!
Aasheesh

**Comment by AasheeshMahammad** [comment]
Functionality has been Implemented and published to NPM.
It will take some time to reflect in Insomnia Plugins.
README has been updated for using the new feature.

Thanks,
Aasheesh
